### ISSUE TITLE
default build directory is ignored

### ISSUE THREAD

**Issue by gittywithexcitement** [edsko/atom-cabal#14]
The default build directory is ignored, causing an error when calling `@getConfigOpt 'buildDir'`

###### stack trace:
```
TypeError: Cannot read property 'trim' of undefined
  at Object.module.exports.Cabal.getConfigOpt (/home/dank/.atom/packages/cabal/lib/cabal.coffee:105:17)
  at Object.module.exports.Cabal.cabalBuild (/home/dank/.atom/packages/cabal/lib/cabal.coffee:53:17)
  at atom-workspace.subscriptions.add.atom.commands.add.cabal:build (/home/dank/.atom/packages/cabal/lib/cabal.coffee:23:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)

```

The problem is compounded by the fact that if I set the build directory to 'dist', which is supposedly the default, my setting is wiped/ignored! The setting is not wiped if I supply some other string besides 'dist'.

Although when I try some other value (not 'dist') for my build directory, I still get this error. Hmm. I tried putting in a value for all build directories (even though I told it to use ghc 7.10), but still same error.

Atom 0.201.0
Ubuntu Linux

**Comment by edsko** [comment]
Hmmm, I think this is due to the fact that the repo is named differently to the package. Fixing now.

**Comment by edsko** [comment]
Released as 0.0.15. Let me know if it works for you.

**Comment by gittywithexcitement** [comment]
Fast response, @edsko , thanks!
Well, all the settings disappeared. Not even the settings button exists now. Was that the intent?

**Comment by gittywithexcitement** [comment]
I ran build, and got error: **'cabal' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.**

Cabal is indeed on my path.

**Comment by edsko** [comment]
Settings disappeared completely? That's very strange. Are you sure? Maybe restart Atom completely?

**Comment by edsko** [comment]
As regards PATH, this can be a little confusing, because what PATH does the `Atom` process inherit? It might not be the same path as you are using in your shell.

**Comment by gittywithexcitement** [comment]
Ah, I had to restart Atom. That fixed the settings thing.
You're right, running atom from the shell, where it can pick up my cabal path, fixed it.
We're all good here, thanks!

**Comment by edsko** [comment]
Excellent! Glad it works for you :)
